name:                cancon
version:             0.1.0.0
github:              "vizaxo/Cancon"
author:              "Vizaxo"
maintainer:          ""
copyright:           "Vizaxo"

extra-source-files:
- Readme.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/vizaxo/Cancon#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- parsec

library:
  source-dirs: src
